overrides:
  '@angular/common@<19.2.16': '>=19.2.16'
  '@angular/core@<10.2.5': '>=10.2.5'
  ansi-html@<0.0.8: '>=0.0.8'
  braces@<3.0.3: '>=3.0.3'
  cookie@<0.7.0: '>=0.7.0'
  debug@>=4.0.0 <4.3.1: '>=4.3.1'
  form-data@<2.5.4: '>=2.5.4'
  http-cache-semantics@<4.1.1: '>=4.1.1'
  http-proxy-middleware@<2.0.7: '>=2.0.7'
  ip@<1.1.9: '>=1.1.9'
  karma@<6.3.14: '>=6.3.14'
  karma@<6.3.16: '>=6.3.16'
  loader-utils@>=2.0.0 <2.0.3: '>=2.0.3'
  loader-utils@>=2.0.0 <2.0.4: '>=2.0.4'
  micromatch@<4.0.8: '>=4.0.8'
  minimatch@<3.0.5: '>=3.0.5'
  moment@<2.29.2: '>=2.29.2'
  moment@>=2.18.0 <2.29.4: '>=2.29.4'
  node-forge@<1.0.0: '>=1.0.0'
  node-forge@<1.3.0: '>=1.3.0'
  node-forge@<1.3.2: '>=1.3.2'
  nth-check@<2.0.1: '>=2.0.1'
  postcss@<7.0.36: '>=7.0.36'
  postcss@<8.4.31: '>=8.4.31'
  postcss@>=7.0.0 <7.0.36: '>=7.0.36'
  rollup@<2.79.2: '>=2.79.2'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
  tar@<6.2.1: '>=6.2.1'
  terser@<4.8.1: '>=4.8.1'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  ua-parser-js@<0.7.22: '>=0.7.22'
  ua-parser-js@<0.7.23: '>=0.7.23'
  ua-parser-js@>=0.7.14 <0.7.24: '>=0.7.24'
  webpack-dev-middleware@<=5.3.3: '>=5.3.4'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
  webpack-subresource-integrity@<1.5.1: '>=1.5.1'
  xml2js@<0.5.0: '>=0.5.0'
